### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Lucifierus/JavaPriceProject#1]
1. - [x] Не совсем понятно, почему класс `Product` сделан отдельным классом, а класс `Price` вложенным в него.
2. - [x] Все поля классов следует делать приватными.
3. - [x] Как минимум для `Product` и `Price` следует переопределить методы `hashCode` и `equals`.
4. - [x] Метод получения цены в копейках следует перенести в `Price`.
5. - [x] Вероятно, для `Price` имеет смысл сделать дополнительный конструктор, принимающий сумму в копейках.
6. - [x] У `PriceMap` должен быть конструктор по умолчанию, т.е. без параметров, который создаёт пустой прейскурант.
7. - [x] Конструктор, который принимает `Map`, должен копировать её.
8. - [x] Все целочисленные переменные и аргументы, кроме `code`, следует сделать типа `int`, а не `Integer`. 
9. - [x] Следует как-нибудь обработать ситуацию добавления продукта с кодом, который уже есть, и удаления несуществующего продукта.
10. - [x] Немного странно проверять `changePrice` через `purchase`. Почему бы просто не проверить цену. Для этого нужно либо добавить `getPrice` аналогичный `getName`, либо получить цену через `getProduct`.
11. - [x] Нет никакого смысла в запоминании ожидаемых результатов вычисления цены в переменные. Это бы ещё имело смысл, если бы Вы их там вычисляли, а так лучше прямо передать числовые значения в `assertEquals`. Кстати, первым аргументом следует ставить ожидаемое значение, а не проверяемое (в двух последних тестах у Вас наоборот).

**Comment by Luciferuz** [comment]
Исправил, проверьте, пожалуйста.

**Comment by maximpetrov** [comment]
1. В классе `Price` не хватает getter'ов. Сейчас пользователь Вашего класса может только посмотреть цену в копейках. У класса `Product` есть getter'ы, но они package-private, что тоже не даёт пользователю нормально воспользоваться Вашим классом (getter'ы нужно сделать public).
2. По поводу замечания 9. Во-первых, Вы сделали ровно наоборот относительно того, о чём мы с Вами говорили. Добавление Вы оставили как было, а при попытке удалить несуществующий объект кидаете исключение. А мы говорили о том, что не удалить объект, которого не было, не так страшно, ведь в результате его всё равно не будет в `Map`, как и хотел пользователь (хотя, конечно, вопрос, как так получилось, что мы хотим удалить несуществующий объект). Так что достаточно просто вернуть `false` в таком случае. А вот при добавлении объекта, код которого уже есть в `Map`, нет варианта обработки ситуации, который всех устроит. Если просто заменить существующий объект, то этот объект незаметно потеряется. Если не добавлять, то опять же незаметно потеряется добавляемый объект. Так что в этой ситуации логичнее выбросить исключение.
3. Кстати, в `deleteProduct` Вы зря вызываете `remove` два раза, он удаляет и с первого раза.

**Comment by maximpetrov** [comment]
В методах `changeName`, `changePrice`, `purchase`, `getName` Вы ищете продукт по коду и вызываете на нём разные методы. Если продукта с таким кодом нет, то `get` вернёт `null`, который приведёт к `NullPointerException`. Это не очень хорошо, лучше кинуть какое-нибудь другое исключение, например, `IllegalArgumentException` с соответствующим сообщением. Кстати, добавьте сообщение в исключение, выбрасываемое в `addProduct`.

**Comment by maximpetrov** [comment]
Вместо того, чтобы сначала проверять наличие товара, а потом получать его (то есть искать два раза одно и то же), лучше один раз получить его в переменную через `get`, проверить переменную на `null`, а потом сделать с переменной то, что нужно.

**Comment by Luciferuz** [comment]
Исправил.
